### ISSUE TITLE
Switch to Scapy v2.4.0?

### ISSUE THREAD

**Issue by guedou** [m13253/wifijam#1]
I noticed that your are using an outdate Scapy fork diverged, that does not follow evolutions and fixes from https://github.com/secdev/scapy

You should consider switching to `scapy` in you requirements.txt

**Comment by m13253** [comment]
Thank you for your report!

I am willing to follow the latest update.
But I need to grab my laptop to check the compatibility before upgrading, that would take some days.
Have you done any compatibility checks?

**Comment by guedou** [comment]
There is no hurry as this is was only a friendly reminder =)
The main difference is that fou need to use raw() instead of str() to build packets.

I can assist if you have issues.

**Comment by m13253** [comment]
Okay! Thank you!

I am currently on a Mac and obviously this code does not work on it.
I will do the test when I finish my trip and have access to my Linux laptop.

Or if you run it successfully, I will upgrade the dependency.

**Comment by guedou** [comment]
FYI, Scapy v2.4.0 works like a charm on OSX without external dependency. 

Wireless sniffing now works natively, see https://github.com/secdev/scapy/pull/1215 If you can test injection, that will be awesome =)

**Comment by m13253** [comment]
> Wireless sniffing now works natively, see secdev/scapy#1215 If you can test injection, that will be awesome =)

Injection does not work very well. (neither `scapy` nor `scapy-python3`)
No errors are reported but I can't see my station using my mobile phone.
I think I have got some configuration wrong, so I will keep trying.

**Comment by m13253** [comment]
I tested Scapy 2.4.0 on Linux. It worked like a charm!
For macOS, I have no idea. I will continue working on that.

This issue is fixed in commit 9b1d6459e9e5dee017be4238424c7f2d61b2f1d8.

**Comment by guedou** [comment]
Awesome !
