### ISSUE TITLE
Feature Request: Change Ssids in runtime

### ISSUE THREAD

**Issue by phenomenoide** [m13253/wifijam#2]
Can you add a function to change the ssids names at runtime? (i like to take for example the value or thermometer and i like to put as a ssid name). Thanks.

**Comment by m13253** [comment]
Thank you for your incoming message.
The SSIDs can be changed at runtime. But your Wi-Fi capable devices may cache the recently discovered SSIDs for a minute or two, causing you to also see those older SSIDs.

This project is provided “as is”, for the hope it may provide helpful knowledge.
I consider this project complete, thus I don’t plan to add any new features.
You may do any improvement as you like, as long as you obey the copyright agreements.
